package ec.com.todo.apptasks.user.entity;


import ec.com.todo.apptasks.board.entity.Board;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@Table(name = "users")
@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_seq")
    @SequenceGenerator(name = "user_seq", sequenceName = "user_sequence", allocationSize = 1, initialValue = 1000)
    private Long id;
    private String name;
    private String username;
    private String password;
    private Boolean isActive;

    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Board> boards;

    @PrePersist
    protected void onCreate(){
        this.id = null; // Assuming the ID is auto-generated by the database
        this.isActive = true;
        this.boards = new ArrayList<>();// Default value for isActive
    }
}
