package ec.com.todo.apptasks.user.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@Table(name = "users")
@Entity
public class User {
    private Long id;
    private String name;
    private String username;
    private String password;
    private Boolean isActive;

    @PrePersist
    protected void onCreate(){
        this.id = null; // Assuming the ID is auto-generated by the database
        this.isActive = true; // Default value for isActive
    }
}
